CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENT] [int] NOT NULL,
[CANVENT] [int] NOT NULL,
[IDVEN] [int] NOT NULL,
[IDPRO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [Venta_Detalle_pk] PRIMARY KEY CLUSTERED ([IDVENT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [Venta_Detalle_PRODUCTO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTO] ([IDPRO])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [Venta_Detalle_VENTA] FOREIGN KEY ([IDVEN]) REFERENCES [dbo].[VENTA] ([IDVEN])
GO
