CREATE TABLE [dbo].[VENTA]
(
[IDVEN] [int] NOT NULL,
[FECVEN] [datetime] NOT NULL,
[IDEMP] [int] NOT NULL,
[IDCLI] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_pk] PRIMARY KEY CLUSTERED ([IDVEN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_CLIENTE] FOREIGN KEY ([IDCLI]) REFERENCES [dbo].[CLIENTE] ([IDCLI])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_Empleado] FOREIGN KEY ([IDEMP]) REFERENCES [dbo].[EMPLEADO] ([IDEMP])
GO
