CREATE TABLE [dbo].[UBIGEO]
(
[IDUBI] [int] NOT NULL,
[DEPUBI] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PROUBI] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DISUBI] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UBIGEO] ADD CONSTRAINT [UBIGEO_pk] PRIMARY KEY CLUSTERED ([IDUBI]) ON [PRIMARY]
GO
