CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL,
[NOMPRO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREPRO] [decimal] (5, 2) NOT NULL,
[DESPRO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [Producto_pk] PRIMARY KEY CLUSTERED ([IDPRO]) ON [PRIMARY]
GO
