CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREPRO] [decimal] (5, 2) NOT NULL,
[DESPRO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PK__PRODUCTO__98FA2D917A7F940F] PRIMARY KEY CLUSTERED ([IDPRO]) ON [PRIMARY]
GO
