CREATE TABLE [dbo].[CLIENTE]
(
[IDCLI] [int] NOT NULL IDENTITY(1, 1),
[DNICLI] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMCLI] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APECLI] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELCLI] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[EMACLI] [varchar] (60) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTCLI] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDUBI] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [PK__CLIENTE__91A8D745C3DBCF6B] PRIMARY KEY CLUSTERED ([IDCLI]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_UBIGEO] FOREIGN KEY ([IDUBI]) REFERENCES [dbo].[UBIGEO] ([IDUBI])
GO
